<?php

namespace Nadoeco\NadoecoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function byFactures($utilisateur){
        $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.utilisateur = :utilisateur')
                    ->andWhere('u.valider = 1')
                    ->andWhere('u.reference != 0 ')
                    ->setParameter('utilisateur',$utilisateur);
                    

        return $qb->getQuery()->getResult();

    }
    public function byDateCommande($date){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.date > :date')
            ->andwhere('u.valider = 1')
            ->orderBy('u.id')
            ->setParameter('date',$date);


        return $qb->getQuery()->getResult();

    }
}
