<?php

namespace Nadoeco\NadoecoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findArray($array){
        $rq = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $rq->getQuery()->getResult();
    }
    public function  byCategorie($categorie){
        $rq = $this->createQueryBuilder('u')
                   ->select('u')
                   ->where('u.categories=:categorie')
                    ->orderBy('u.id')
                    ->setParameter('categorie',$categorie);
        return $rq->getQuery()->getResult();
    }

    public function recherche($chaine){
        $rq = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.nom like :chaine')
                    ->andWhere('u.disponible = 1')
                    ->orderBy('u.id')
                    ->setParameter('chaine',$chaine);
        return $rq->getQuery()->getResult();
    }
}
