nadoeco_utilisateur:
    resource: "@NadoecoUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

pages_pages:
    resource: "@PagesPagesBundle/Resources/config/routing.yml"
    prefix:   /

nadoeco_nadoeco:
    resource: "@NadoecoNadoecoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

