produitsAdmin:
    path:     /
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:index" }

produits_show:
    path:     /{id}/show
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:show" }

produits_new:
    path:     /new
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:new" }

produits_create:
    path:     /create
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:create" }
    methods:  POST

produits_edit:
    path:     /{id}/edit
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:edit" }

produits_update:
    path:     /{id}/update
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:update" }
    methods:  [POST, PUT]

produits_delete:
    path:     /{id}/delete
    defaults: { _controller: "NadoecoNadoecoBundle:ProduitsAdmin:delete" }
    methods:  [POST, DELETE]
