<?php

namespace Pages\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
   public function findByRemove(){
       $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->where('p.deletedAt IS NOT NULL')
                   ->orderBy('p.id')
                   ->getQuery();
       return $qb->getResult();
   }
}
